version: 2
updates:
  - package-ecosystem: pip
    directory: "lambda/src/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: terraform
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: terraform
    directory: "/tests/test_create_package_separately"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
